version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    environment:
      - APP_NAME=WealthSphere
      - API_PREFIX=/api
      - DEBUG=True
      - DATABASE_URL=sqlite:///./wealthsphere.db
      - SECRET_KEY=dev_secret_key_change_in_production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - TAX_YEAR=2023
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      # For client-side browser requests
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      # Development mode settings
      - NODE_ENV=development
      - ESLINT_NO_DEV_ERRORS=true
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000 || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: npm run dev

volumes:
  backend_data: 